### PR TITLE
Memet done project

### PR DESCRIPTION
**Pull request by MemetKayaQA**
good project

### CODE REVIEW

**Comment by akalexiskelly** [comment]
good
it's very very good!!!

**Comment by mucahitekin** [comment]
lets merge

**Review by akalexiskelly — CHANGES_REQUESTED** [review]
looking good

**Comment by turgayozkan16** [comment]
we can merge

**Review by turgayozkan16 — APPROVED** [review]
we can merge

**Comment by MemetKayaQA** [comment]
okay

**Review by akalexiskelly — APPROVED** [review]
good job approved

**Pull request merged**
